### PR TITLE
calibration instruction v0 -fh

### PR DESCRIPTION
**Pull request by haslbeck**
wrote instructions for the calibration script, please review and accept @NoorKosterUvA

### CODE REVIEW

**Review by noorkoster — APPROVED** [review]
Nice! -nk

**Review by noorkoster — APPROVED** [review]
Nice -nk

**Review by noorkoster — APPROVED** [review]
Nice! -nk

**Review by NoorKosterUvA — APPROVED** [review]
Third attempt -nk

**Pull request merged**
