### PR TITLE
Create import_data_carlo.py (work in progress) -cf

### PR DESCRIPTION
**Pull request by cfuselli**
Just a little preparation for tomorrow in the lab, code to read data from computer just a little bit simplified.

### CODE REVIEW

**Review by haslbeck — CHANGES_REQUESTED** [review]
but why do you redo the import_data when there is already a data taking "framework" (way way simpler) in live.py or simple_calibration.py (both in Calibration/) @cfuselli , I would suggest to use this as the base instead of this mess here -fh

**Review by haslbeck — COMMENTED** [review]
the arduino code looks ok -fh

**Comment by haslbeck** [comment]
will merge anyways to pull the arduino and im too lazy to cherry pick but I wouldnt use the heavy import data @cfuselli

**Review by haslbeck — APPROVED** [review]
see comments -fh

**Comment by cfuselli** [comment]
I'll call you tomorrow and we can talk about it @haslbeck

**Pull request merged**
