### PR TITLE
Debug daq friday 18th

### PR DESCRIPTION
**Pull request by haslbeck**
@cfuselli

### CODE REVIEW

**Comment by haslbeck** [comment]
this one

**Comment by haslbeck** [comment]
huhu @cfuselli

**Comment by haslbeck** [comment]
this one @cfuselli @NoorKosterUvA

**Review by NoorKosterUvA — APPROVED** [review]
nice -nk

**Review by NoorKosterUvA — APPROVED** [review]
great -nk

**Pull request merged**
